### ISSUE TITLE
Can't add new group to existing Layers

### ISSUE THREAD

**Issue by tkokev** [ROGUE-JCTD/rogue_geonode#104]
Here is my flow:
-add several layers in GeoNode
-use the Admin web interface to create a new group, "testgroup", with no permissions
-use the Admin web interface to add an existing user to the group
-browse back to geonode
-select a layer at random
-click "change layer permissions" button
-expand "Who can manage it?
-under "The following groups:" box, start typing the group name "testgroup"
-"No matches found" text is displayed

**Comment by garnertb** [comment]
Create the group using the "Group Create" page vs the admin console: /groups/create/.

**Comment by tkokev** [comment]
Thanks! That worked.
