### ISSUE TITLE
WMS Cascade Layers Error

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/rogue_geonode#67]
When adding WMS Cascade layers with the --skip-unadvertised tag.  It throws a "has no attribute 'advertised'" error when run w/ a CascadeWMS layer.

root@rogue-geoserver-bn:~# /var/lib/geonode/bin/python /var/lib/geonode/rogue_geonode/manage.py updatelayers --ignore-errors --remove-deleted --skip-unadvertised
AttributeError: 'WmsLayer' object has no attribute 'advertised'
root@rogue-geoserver-bn:~#

-- Fix needs to be pushed up-stream once verified --

**Comment by garnertb** [comment]
Closing since there is no work required from us on this.
