### ISSUE TITLE
Over-ride help in Profile Menu with GeoSHAPE help

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/rogue_geonode#74]
The default help in GeoNode isn't very in-depth and unfortunately the GeoSHAPE user documentation is only accessible on the main screen. 

The Help button under the profile menu should take you to the GeoSHAPE docs _and_ it should open the documentation in another tab to keep you from losing your map.

**Comment by garnertb** [comment]
Fixed in https://github.com/ROGUE-JCTD/rogue-cookbook/commit/181169517e4fe09c1fd51233b55b2592fb2b1bba.

As it stands, the documentation will not open in a new tab since that would require us to override the base GeoNode template which isn't worth the maintenance expense.
