### ISSUE TITLE
Upload layers dialog doesn't clear 

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/rogue_geonode#78]
If you remove a layer or clear the layer in the upload layer dialog (prior or after attempting to upload), the old data doesn't clear. To reproduce, select a layer to upload, choose clear or remove, then choose another layer. The first layer will show up in the UI again. I had to reload the page to clear the old layer info.

**Comment by garnertb** [comment]
Fixed in https://github.com/GeoNode/geonode/commit/c3835276ed6f8013afb092ad70e22ce40dd31538.
