### ISSUE TITLE
Paver cannot access for download ROGUE_GEOSERVER_URL

### ISSUE THREAD

**Issue by SarinKesphanich** [ROGUE-JCTD/rogue_geonode#94]
Paver cannot access for download at ROGUE_GEOSERVER_URL

ROGUE_GEOSERVER_URL="http://jenkins.rogue.lmnsolutions.com/userContent/geoserver.war"

**Comment by garnertb** [comment]
Don't use paver to set up this project,  follow these instructions instead: https://docs.google.com/document/d/1KMpk6dXuqvwfEi0pfRpaGY62j6ikoYtpYUPU0sJQAmk/edit#heading=h.mp9cjwd13vey.

pavement.py should probably just be removed, since I don't *think* its used for anything in this project.
